### ISSUE TITLE
Complete the documentation

### ISSUE THREAD

**Issue by bryonbaker** [os-climate/markets-pricing-service#7]
This service is reusable and extensible. Document how others can reuse and repurpose the service

**Comment by MichaelTiemannOSC** [comment]
Please create a demo notebook in https://github.com/os-climate/data-platform-demo and link to that in the documentation you write.  Could be something as simple as showing USD/EUR exchange rates for both a historical date and "the most recent rate we have", and perhaps a series showing a range with a time-grain resolution.  Bonus points for creating a SuperSet display.

**Comment by MichaelTiemannOSC** [comment]
Re-upping the request to implement a demo notebook since Jupyter/Python is the prototyping standard for all workstreams.  As a python developer, I cannot figure out how to make a call to this service to get the USD price of a EUR on 2021-12-31.

@caldeirav @erikerlandson

**Comment by bryonbaker** [comment]
Hi
You don't make a call. It publishes the prices to a kafka topic once a day. You use trino to query the topic. 
Vincent wrote a demo notebook to demo it.

**Comment by MichaelTiemannOSC** [comment]
Got it.  Looks like this is that notebook: https://github.com/os-climate/data-platform-demo/blob/master/notebooks/ecb-fx-query.ipynb.  I'll add info to the README.

**Comment by bryonbaker** [comment]
I did notice that occasionally the ECB back end returns service unavailable so a few days data is missing. I am going to raise a bug and have it retry. Later this week I will find the missing data and place it on the topic so the full set is there.
